---
- name: Listen for file
  hosts: localhost
  sources:
    - ansible.eda.file:
        files:
          - /opt/ansible/fact.yml

  rules:
    - name: Match Malware detected-malware event
      condition:
        exec == "True"
      action:
        run_job_template:
          name: "test-action"
          organization: Default
          job_args:
            extra_vars:
              text: "{{ val1 }}"
